from dataclasses import dataclass

from dataset import Question
from llm import ClaudeClient, LLMResponse
from parser import AnswerParser, ANSWER_TO_INDEX
from prompt import Prompt, build_prompt

REPAIR_MODEL = "claude-haiku-4-5-20251001"

REPAIR_TOOL = {
    "name": "translate_answer",
    "description": (
        "Translate the final answer only into one letter: "
        "A, B, C, or D."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "answer": {
                "type": "string",
                "enum": ["A", "B", "C", "D"],
            }
        },

        "required": ["answer"],
    },
}

REPAIR_INSTRUCTION = """
The following text is the raw response generated by another language model.

Your task is NOT to answer the original question again.

Instead, determine which option (A, B, C, or D) the response refers to.

Always use the provided translate_answer tool.

Do not perform additional reasoning.
""".strip()

@dataclass(frozen=True)
class InferenceResult:
    
    question_index: int
    prediction: int
    raw_response: str
    repaired: bool
    repair_response: str | None
    llm_response: LLMResponse
    repair_llm_response: LLMResponse | None


class InferenceEngine:

    def __init__(self, llm_client: ClaudeClient, skill=None, parser: AnswerParser | None = None):
       
        self.llm_client = llm_client
        self.skill = skill

        if parser is None:
            parser = AnswerParser()

        self.parser = parser


    def run(self, question: Question, retrieved_chunks=None) -> InferenceResult:

        prompt = build_prompt(
            question=question,
            skill=self.skill,
            retrieved_chunks=retrieved_chunks,
        )

        llm_response = self.llm_client.generate(prompt)

        prediction = self.parser.parse(llm_response.text)

        if prediction != -1:

            return InferenceResult(
                question_index=question.index,
                prediction=prediction,
                raw_response=llm_response.text,
                repaired=False,
                repair_response=None,
                llm_response=llm_response,
                repair_llm_response=None,
            )


        repair_llm_response, repair_answer = (
            self._repair_answer(
                raw_response=llm_response.text
            )
        )

        if repair_answer is not None:
            repaired_prediction = ANSWER_TO_INDEX[repair_answer]

        else:
            repaired_prediction = -1

        return InferenceResult(
            question_index=question.index,
            prediction=repaired_prediction,
            raw_response=llm_response.text,
            repaired=True,
            repair_response=repair_answer,
            llm_response=llm_response,
            repair_llm_response=repair_llm_response,
        )



    def _repair_answer(self, raw_response: str) -> tuple[LLMResponse, str | None]:

        repair_prompt = Prompt(
            instruction=REPAIR_INSTRUCTION,
            question=(
                "Previous model response:\n"
                + raw_response
            ),
            output_prefix="",
            mode="repair",
        )

        repair_response = self.llm_client.generate_with_tool(
            prompt=repair_prompt,
            model=REPAIR_MODEL,
            tool=REPAIR_TOOL,
            tool_choice={
                "type": "tool",
                "name": "translate_answer",
            }
        )

        repair_answer = None
        for block in repair_response.raw_content:
            if getattr(block, 'type', None) == "tool_use":
                tool_input =getattr(block, 'input', None)
                if isinstance(tool_input, dict):
                    answer = tool_input.get("answer")
                    if answer in ANSWER_TO_INDEX:
                        repair_answer = answer
                break

        return (repair_response, repair_answer)



def run_inference(
    question: Question,
    llm_client: ClaudeClient,
    skill=None,
    retrieved_chunks=None,
) -> InferenceResult:

    engine = InferenceEngine(
        llm_client=llm_client,
        skill=skill,
    )

    return engine.run(
        question=question,
        retrieved_chunks=retrieved_chunks,
    )